### PR TITLE
Highscore

### PR DESCRIPTION
**Pull request by Tomas2h**
Added a highscore feature to the game and the game is now able to return after losing of winning.
<feature, organisation, testing

### CODE REVIEW

**Comment by Austaon** [comment]
Looks very nice! Also the commits timeline made me laugh ;)

<review

**Comment by ardwennem2** [comment]
Ziet er goed uit
<review

**Comment by HugoReijm** [comment]
nice added feature
<review

**Comment by larsvandekamp** [comment]
The highscores look very good, nice to have user input as well!
<review

**Pull request merged**
