### PR TITLE
New menu for protagonist Selection

### PR DESCRIPTION
**Pull request by larsvandekamp**
Hey guys, I added buttons with the different protagonist sprites. Only able to select one and should be able to be easily integrated in the code being made by Hugo and Aurel. Let me know what you guys think. Oh yeah I also changed a few minor details to remove certain bugs. 

<feature, user-interface, bug

### CODE REVIEW

**Comment by weikeu** [comment]
OK, the new menu looks quite nice
<review

**Comment by Austaon** [comment]
Good that you changed back the testing values ;)
Will look at the menu and such tomorrow
<review

**Comment by larsvandekamp** [comment]
Thank you for pointing them out Aurel, used them to make the build a bit easier and forgot about them in the end!
<review

**Comment by Austaon** [comment]
Looks good! I only thing the sprite for the laser protagonist needs to be cleaned up a bit, but we'll handle this in the MultipleProtagonist branch.
<review

**Pull request merged**
