### PR TITLE
Endless mode

### PR DESCRIPTION
**Pull request by ardwennem2**
Added endlessmode instead of normal mode
<feature

### CODE REVIEW

**Comment by larsvandekamp** [comment]
Enemies are currently spawning on top of each other, maybe put in a minimum distance they need to get and when all enemies are gone the method is called instantly. 
<review

**Comment by ardwennem2** [comment]
Enemies must now be at a certain distance before new enemies are spawned

**Comment by Austaon** [comment]
Looks really nice, and it gets really difficult in the end!
However, I would look into the positioning and maybe not spawning *some* enemies (thus leaving a hole in the *structure*)

**Comment by ardwennem2** [comment]
positioning and holes fixed :D

**Comment by Austaon** [comment]
Awesome!
<review

**Pull request merged**
