### PR TITLE
Collision branch

### PR DESCRIPTION
**Pull request by Austaon**
Refactoring for the collision to make sure the Game class has less responsibility.

Collision now works following a Strategy pattern and lambda functions, which allows for more customized collision, instead of hardcoded results and a different function for all collision types.

Refactoring was done in multiple classes to ensure that the collision implementation could be as broad as possible while still allowing for refined execution.

<bug, feature, documentation, layout, naming, logic, performance, organisation, interface, user-interface

### CODE REVIEW

**Comment by weikeu** [comment]
This change is quite large, I will have to review it in-depth tonight.

**Comment by ardwennem2** [comment]
looks good
<review

**Comment by HugoReijm** [comment]
design patterns for the win. lekker bezig
<review

**Comment by Tomas2h** [comment]
Looks very nice. Well done on the design pattern and improving the code style
<review

**Comment by larsvandekamp** [comment]
Nice work on the collision refactoring! 
<review

**Pull request merged**
